version: "3.8"
services:
  sat-track:
    build: ./
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./public
        target: /app/public
    command: npm run dev